### ISSUE TITLE
Download da xml mdf-e

### ISSUE THREAD

**Issue by luismareze** [nfephp-org/sped-mdfe#106]
Estou tentando baixar o xml da mdf-e consultando pela chave conforme abaixo. Mas obviamente o response apenas traz dados do evento em si.

Como é possivel gerar o xml completo para depois eu gerar o damdfe?

$response = $nfe->sefazConsultaChave($chave);

**Comment by cleitonperin** [comment]
boa tarde, esse servico nao retorna o xml, alias a sefaz nao tem nenhum serviço que baixa as notas que voce emitiu, esse servico ai busca os eventos que foram feitos em cima da chave de acesso.
