### ISSUE TITLE
Duvida tag infLotacao

### ISSUE THREAD

**Issue by f3lpz** [nfephp-org/sped-mdfe#116]
Olá,

Estou montando um XML do MDF-e, porém ao informar apenas um documento, entrou na validação abaixo e não gerou o documento.  

```
if (($tpEmit == 1 || $tpEmit == 3) && empty($this->infLotacao) && ($this->contaDoc($this->infCTe) + $this->contaDoc($this->infNFe) + $this->contaDoc($this->infMDFeTransp)) == 1) {
                $this->errors[] = "Tag infLotacao é obrigatória quando só existir um Documento informado!";
}
```

Na norma técnica 2020.20 página 10  encontrei o seguinte: 

> Se modal rodoviário e Tipo Emitente for igual a Prestador de Serviço de Transporte
> (tpEmit=1) ou transportador que emitirá CT-e globalizado (tpEmit=3) e MDF-e possuir
> apenas um DF-e transportado no grupo infDoc:
> O grupo de informações da carga lotação (infLotacao) deve estar informado
> Observação: regra de validação aplicável em produção a partir de 06/07/2020
> [COVID-19]
> **Facult**. 726 Rej.

Está marcando como facultativo, fiz um teste enviando sem essa tag nos moldes dessa validação e enviou normal. Gostaria de saber se está de acordo isso que mencionei.

Grato!
_

**Comment by robmachado** [comment]
Como você mesmo leu esse requisito foi ADIADO para 06/07/2020 devido a CIVID-19 (desculpa geral para tudo)
.. ou seja a partir da próxima segunda feira a tag infLotacao será exigida nesses casos

**Comment by f3lpz** [comment]
Esqueci de mencionar, foi prorrogado novamente p/ dia 08/09/2020. Porém o ambiente de homologação já está implementado segundo a norma técnica 02.2020 (desde 09/03/2020). Então deveria ser exigido, certo? 

 Fonte https://dfe-portal.svrs.rs.gov.br/Mdfe/Avisos/1175

Grato!
