### ISSUE TITLE
XML Encerramento

### ISSUE THREAD

**Issue by marcelobacha** [nfephp-org/sped-mdfe#118]
Bom dia. 
Gostaria de agradecer pelo excelente trabalho nesta biblioteca. No caso encerramento do MDF-e preciso pegar todo o XML de encerramento assinado. Como faço isso? 
Obrigado desde ja

**Comment by robmachado** [comment]
Precisa explicar melhor !!
Você quer o xml de encerramento que você envia ou o que você recebe no retorno ?

**Comment by marcelobacha** [comment]
RobMachado,

Muito obrigado, era o $tools->lastRequest que estava querendo. Obrigado pela rápida resposta.
