### ISSUE TITLE
Verificação de código ean

### ISSUE THREAD

**Issue by xxdannilinxx** [nfephp-org/sped-mdfe#122]
Boa tarde, no sped-nfe tem um método pra verificar o código ean, será que não conseguíamos implementar no sped-mdfe pra verificar o código ean do produto predominante?

**Comment by robmachado** [comment]
Claro que sim.
O pacote sped-gtin pode ser uma dependência incluída no sped-mdfe e quando tiver GTIN no produto Predominante, o mesmo pode ser verificado. Mas podem haver implicações, teria de ler o manual atentamente e verificar se isso é possível, e colocar essa verificação com esses cuidados na classe Make() e retornar erro caso o GTIN informado seja incorreto.

Apenas não podemos apenas colocar essa validação sem entender e testar as possibilidades e consequências disso.
Fique a vontade em contribuir !!
