### ISSUE TITLE
Undefined property: stdClass::$infRec

### ISSUE THREAD

**Issue by desenvolvimento03polidados** [nfephp-org/sped-mdfe#135]
alguém saberia o motivo do erro? 
ele acontece ao tentar enviar o MDF-e

Código em questão:
public function transmitir($signXml)
	{
		try {
			$resp = $this->tools->sefazEnviaLote([$signXml], rand(1, 10000));

			$st = new Standardize();
			$std = $st->toStd($resp);

			sleep(3);

			$recibo = $std->infRec->nRec; 

			$resp = $this->tools->sefazConsultaRecibo($recibo);
			$std = $st->toStd($resp);

	               if (!isset($std->protMDFe)) {
				return [
					'erro' => true,
					'message' => 'Tente enviar novamente em minutos!',
					'cStat' => '999'
				];
			}
}

**Comment by DevNF** [comment]
Cara, pelo que consegui ver nas documentações da sefaz, o campo infRec só é gerado quando o lote foi aceito, acredito que o lote que está tentando enviar esta sendo rejeitado por algum erro de preenchimento, tente verificar o status do lote antes de tentar acessar a posição "$std->infRec->nRec" (Pois é no momento em que você tenta acessar o grupo que causa a exception que está no título)

![image](https://user-images.githubusercontent.com/90803174/173136736-7b1a1859-6db7-4d12-8638-4dce2578a963.png)

Fonte: https://www.confaz.fazenda.gov.br/legislacao/arquivo-manuais/moc_mdfe_visaogeral_v3-00a.pdf

**Comment by cleitonperin** [comment]
ola, no caso do MDF-e ele é síncrono, portanto não possui recibo nem lote, quando você envia já ira obter direto a rejeição ou a autorização do documento.
