### ISSUE TITLE
Problema com o grupo tagcodAgPorto

### ISSUE THREAD

**Issue by DevNF** [nfephp-org/sped-mdfe#136]
Bom dia, tudo bem? Estamos enfrentando problemas ao montar a tag do código de agendamento do porto no MDF-e, sempre que chamo a função ele da a seguinte mensagem

![image](https://user-images.githubusercontent.com/90803174/173056580-cd676ceb-ee81-4f45-8040-d4a983bf995d.png)

Não sei se tem uma ordem certa para passar essa campo, ou se tem algo que deveria chamar antes, tentei verificar pela classe mas não achei nada

Estou utilizando a versão 4.1 da biblio
Desde ja agradeço e no aguardo

**Comment by cchimbooo** [comment]
Estou tendo o mesmo problema. 

Ontem submeti um #Pull Request para corrigir o mesmo.  Caso tenha pressa é possível fazer um fork com a alteração do código constante no #Pull Request até que o mesmo seja aprovado.

**Comment by cleitonperin** [comment]
Mesclado
