### ISSUE TITLE
Padronizar função "sefazEvento" da classe "Tools"

### ISSUE THREAD

**Issue by Hzin** [nfephp-org/sped-mdfe#142]
Somente esse projeto tem a função `sefazEvento` da classe _Tools_ como `protected`, o que impossibilita a implementação de novos eventos de forma 'avulsa'. Por exemplo, se eu quiser implementar a manifestação do evento '110116', '110117' ou '110118' não consigo, pois o método não permite ser acessado de fora da classe. Poderiam fazer essa mudança por gentilileza?

**Comment by maisonsakamoto** [comment]
Ola Hzin, faz um fork do projeto, implementa a modificação e faz um pull request

**Comment by Hzin** [comment]
@maisonsakamoto PR #143 aberto.

**Comment by maisonsakamoto** [comment]
Obrigado por contribuir!
