### ISSUE TITLE
Emissão síncrona

### ISSUE THREAD

**Issue by MarcosArthur** [nfephp-org/sped-mdfe#147]
A lib já está pronta para emissão no modo síncrona, com as mudanças da NT 2024/001  ?

**Comment by cacio** [comment]
Acho que deve estar, só queria um certeza também sobre isso, sei que tem a função sefazEnviaLote e um paramentro  $indSinc se colocar iqual a 1 ja vai via MDFeRecepcaoSinc , mas preciso de uma certeza dos mestres ai, aguardo.

**Comment by robmachado** [comment]
Emissão sincrona OK já usamos faz tempo
