### ISSUE TITLE
Criar branch develop

### ISSUE THREAD

**Issue by Gleidson2012** [nfephp-org/sped-mdfe#28]

**Comment by robmachado** [comment]
@Gleidson2012 Como não existem ainda TAGs ou seja nenhuma RELEASE foi criada pode usar apenas a branch MASTER, somente depois que existirem RELEASES é devemos nos preocupar com isso.

**Comment by Gleidson2012** [comment]
Entendi.

Porém, as implementações que fiz até o momento seguem a minuta do MDF-e v3.00.

O que fazemos neste caso?

Acho que podemos gerar uma **release** do branch master que suporta a versão v2.00 do MDF-e e o branch develop suportando a v3.00.

**Comment by robmachado** [comment]
haaa .. isso é outra coisa ... vou fazer o seguinte vou criar uma branch v3.0 e podemos usa-la quando entrar  no ar passamos para master e criamos uma tag dessa nova versão

**Comment by robmachado** [comment]
Branch v3.0 criada

**Comment by Gleidson2012** [comment]
Perfeito!
