### ISSUE TITLE
V2.0 - Tag condutores (modal Rodoviario)

### ISSUE THREAD

**Issue by igorwanbarros** [nfephp-org/sped-mdfe#44]
Ao adivionar condutores e reboque(s) a tag condutores fica atrelada a tag veicReboque, onde conforme o manual v1.00a deve ficar junto da tag veicTracao.

Segue exemplo de MDFe com condutores junto da tag veicReboque.

![mdfe](https://cloud.githubusercontent.com/assets/8918508/24165872/61782258-0e50-11e7-899d-841145db042e.png)

**Comment by maisonsakamoto** [comment]
Bom dia, estou atualizando o projeto, hoje estamos na v3.0 então vou fechar essa issue, teste novamente acredito que já tenha sido resolvido essa questão, qualquer coisa pode reabrir a issue, obrigado.
