### ISSUE TITLE
V2.0 - Erro ao executar tag infDoc

### ISSUE THREAD

**Issue by igorwanbarros** [nfephp-org/sped-mdfe#45]
Ao executar o método Make::montaMDFe() é lançada uma exceção de objeto não instanciado.

Ao verificar a possível causa desse erro foi identificado que ao executar o método Make::zTagInfDoc() a classe já adiciona a quantidade de documentos vinculados (NFe, CTe, MDFe Transporte), porém caso ao adicionar a tag Make::tagTot() e não informar ou não hover totais para algum dos documentos é lançado o erro.

**Comment by maisonsakamoto** [comment]
bom dia acredito que essa issue já tenha sido resolvida, irei encerrar, caso seja necessário mais alguma correção favor abrir novamente a issue ou uma nova, obrigado
