### ISSUE TITLE
V2.0 - Tag veicReboque adição de tags

### ISSUE THREAD

**Issue by igorwanbarros** [nfephp-org/sped-mdfe#46]
1. Foi observado que a tag reboque deve ser veicReboque;
2. A tag não possui em seus filhos a tag tpRod;
3. A tag veicReboque não possui a opção de adicionar proprietario (tag prop);

Segue anexo estrutura de tags gerada.
![mdfe2](https://cloud.githubusercontent.com/assets/8918508/24166711/f980085c-0e52-11e7-8680-fef50e27f254.png)

**Comment by maisonsakamoto** [comment]
Bom dia vou encerrar essa issue pois estamos usando atualmente a v3.0, caso sinta necessidade favor abrir outra issue, obrigado
