### ISSUE TITLE
V2.0 - Tag veicTracao

### ISSUE THREAD

**Issue by igorwanbarros** [nfephp-org/sped-mdfe#47]
A tag Make::tagVeicTracao() não possibilita informar todos os campos da tag prop (proprietario), onde conforme manual v1.00a todos (CPF, CNPJ, RNTRC, xNome, IE, UF, tpProp) devem ser informados.

Segue exemplo.
![mdfe3](https://cloud.githubusercontent.com/assets/8918508/24170498/cd2cf028-0e5f-11e7-8210-4e489892c579.png)

**Comment by maisonsakamoto** [comment]
Bom dia vou encerrar essa issue pois estamos usando atualmente a v3.0, caso sinta necessidade favor abrir outra issue, obrigado.
