### ISSUE TITLE
V2.0 - Erro no Schema ao adicionar autorizados e informações adicionais

### ISSUE THREAD

**Issue by igorwanbarros** [nfephp-org/sped-mdfe#48]
Ao adicionar em um MDFe autorizados e informações adicionais ocorre erro de validação do schema.
Ao realizar alguns teste e de verificar o manual foi observado que a tag infAdic deve ser adicionada após a(s) tag(s) autXML ou ao final das demais tags.

Segue exemplo.

![mdfe4](https://cloud.githubusercontent.com/assets/8918508/24170526/e73d13c6-0e5f-11e7-98ed-f20b1582017f.png)

**Comment by maisonsakamoto** [comment]
bom dia acredito que essa issue esteja resolvido, obrigado pela colaboração, caso seja necessario favor abrir outra issue
