### ISSUE TITLE
Erro ao instalar/update v3.0 no composer

### ISSUE THREAD

**Issue by tavinus** [nfephp-org/sped-mdfe#50]
Não estou conseguindo incluir/fazer update pra versao 3.0 no composer.  
O erro é:
```
  Problem 1
    - nfephp-org/sped-mdfe v3.0.x-dev requires nfephp-org/sped-console dev-develop -> no matching package found.
    - nfephp-org/sped-mdfe v3.0.x-dev requires nfephp-org/sped-console dev-develop -> no matching package found.
    - Installation request for nfephp-org/sped-mdfe v3.0.x-dev -> satisfiable by nfephp-org/sped-mdfe[v3.0.x-dev].
```
Acho que o branch dev-develop não existe mais no repo sped-console, mas o json ainda aponta pra ele. Eu estou usando os repos git no composer.  
  
No caso seria só modificar o arquivo [composer.json](https://github.com/nfephp-org/sped-mdfe/blob/master/composer.json) pra `dev-master` em `nfe-php/sped-console`?
Acho que vou fazer um fork e mudar isso pra já poder começar a testar. Se der certo eu mando um PR com essa modificação.

**Comment by robmachado** [comment]
Acredito que o sped-console está ai de GAIATO !!! não tem uso para o mesmo deveria ser retirado do composer.json

**Comment by tavinus** [comment]
Se você fala isso... EU ACREDITO!  
Quem saberia com certeza?  
Posso fazer um PR retirando o sped-console então?  
Pelo que eu vi o sped-console por enquanto só tem uma função?

**Comment by robmachado** [comment]
Na verdade não fui eu que colocou !
Tem outros colegas administrando do MDFe !!
Mas acredito que foi apenas para testes, pois não está sendo usado na classe Make. realmente eu não sei.
Para você fazer testes ai, não tem problema é só remover que não vai afetar nada no funcionamento das classes na sua maquina, ou colocar o repositório master no lugar do dev-develop (pois dev-develop não existe)

**Comment by tavinus** [comment]
Depois de mais de hora pra atualizar meu fork com upstream consegui modificar e importar.  
No caso eu removi o requisito do sped-console e deu certo.  
Mas precisa ver se o ideal é remover ou usar master.  
De qq forma, do jeito que está não funciona...

**Comment by maisonsakamoto** [comment]
Bom dia vou encerrar essa issue , caso sinta necessidade favor abrir novamente postando a dificuldade, obrigado.
