### ISSUE TITLE
Serviço de Consulta não Encerrados [homologação]

### ISSUE THREAD

**Issue by igorwanbarros** [nfephp-org/sped-mdfe#53]
Ocorre erro de cabecalho [Rejeição: Cabecalho - Versao do arquivo XML não suportada] ao realizar consulta de não encerrados pelo webservices do RS.

**Comment by maisonsakamoto** [comment]
acredito que esse problema tenha sido resolvido, favor testar novamente com a versão atual da branch v3.0, caso seja necessário pode abrir novamente a issue reportando a difuldade.
