### ISSUE TITLE
Tenho uma versão estável. O que fazer para aceitar meu PR?

### ISSUE THREAD

**Issue by aloisogomes** [nfephp-org/sped-mdfe#57]
Fala pessoal, eu baixei a versão de desenvolvimento implementei o que faltava para o mdf-e funcionar na versão 3.00 mas, gostaria de saber quais os requisitos para o PR não ser rejeitado?

**Comment by maisonsakamoto** [comment]
bom dia, os requisitos é atender o PSR2, PHP7.

use PHPCBF, PHPCS, PHPUNIT antes de fazer o PR se passar nesses scripts ele não será rejeitado pelo TRAVIS.

Por favor envie os PR na branch v3.0, não envie o projeto inteiro de uma só vez, faço por etapas para que eu possa analisar os trechos e ir aceitando mais rapidamente, se colocar tudo numa pancada só pode ser que eu demore para analisar tudo e na pior das hipóteses um única linha de código em conflito pode deixar todos os outros arquivos pendentes.

Obrigado pela contribuição.
