### ISSUE TITLE
MDFE 3.00

### ISSUE THREAD

**Issue by cacio** [nfephp-org/sped-mdfe#60]
esta versão já esta fazendo para 3.00 ?

**Comment by maisonsakamoto** [comment]
sim, a tanto a branch v3.0 quanto a master

**Comment by cacio** [comment]
Aham , pergunto porque não estou vendo tags novas tipo <seg> , <infANTT> que são obrigatórias para emissão

**Comment by LUCASNDIAS** [comment]
@cacio realmente não estão rsrs.
tem um pull request meu que ainda não foi aceito que eu adicionei as tags...
aguardando...

**Comment by maisonsakamoto** [comment]
Pois é se não me engano eu peguei um fork e dei continuidade, nesse projeto eu não estou com privilégios para aceitar os PR, @gustavodebiasi foi quem aceitou o último PR, teria que ver com a equipe, @robmachado quem esta a frente desse projeto MFDe ?

**Comment by robmachado** [comment]
Quem está a frente é quem tem real INTERESSE e disposição para levar isso adiante !

**Comment by robmachado** [comment]
Nada impede que eu coloque o Mailson como administrador também ! Se ele desejar isso !

**Comment by maisonsakamoto** [comment]
Oi Roberto, então, eu estou disposto a colaborar no MDFe também, eu já fiz todos os testes de homologação, impressão, agora estou finalizando a interface do usuário para iniciar os testes em produção.

Daqui em diante como estarei emitindo MDFe todos os dias posso colaborar ativamente com esse projeto assim como estou ativo no CTe.

**Comment by robmachado** [comment]
Que ótimo Mailson ! vou te colocar lá também então !!

**Comment by maisonsakamoto** [comment]
@LUCASNDIAS os dois PR já comitei, os demais inclusive os meus eu vou dar uma revisada porque o travis reportou erros nesses outros, 
@cacio agora com esse PR é para as tags<seg> e <infANTT> estarem lá, testa e comenta aqui se ficou certo que já encerro essa issue

**Comment by robmachado** [comment]
Maison ! 
podemos melhorar o composer.json, para incluir scripts que podem fazer analise do código e limpeza para atender o PSR2. O ideal é passar todo o código para trabalhar com PHP 7+ eu mesmo estou fazendo isso e em 2018 os outros pacotes serão todos ajustados para aceitar somente PHP7+.
Nesse momento podemos colocar o PHPCBF, PHPCS, PHPUNIT nesses scripts e assim que passar para >= PHP7.0 podemos também incluir o PHPSTAN nesses scripts. Isso ajuda em muito a manter o código limpo e coerente.

**Comment by maisonsakamoto** [comment]
ok

**Comment by maisonsakamoto** [comment]
@cacio então só para alinhar essa issue:
ref a previsão de uma versão estável vou deixar essa issue em aberto:
https://github.com/nfephp-org/sped-mdfe/issues/55

Fiz um PR, ainda tenho mais alguns para fazer mas já estou codando para fazer uma versão de estável, certamente vou codar as tags que são minhas necessidades primeiro, posteriormente vou codar conforme a demanda das issues que forem abertas para atender o público que usa o projeto, e se tiver tempo sobrando irei codar todas as tags que estiverem faltando.
