### ISSUE TITLE
Imagem PDF da MDFe

### ISSUE THREAD

**Issue by amorales84** [nfephp-org/sped-mdfe#62]
Bom dia a todos! Gostaria de saber se alguém está trabalhando no código para gerar o pdf.

**Comment by robmachado** [comment]
Veja sped-da

**Comment by maisonsakamoto** [comment]
Boa tarde @amorales84 nesse projeto:
https://github.com/nfephp-org/sped-da

basta passar o xml que ele monta o pdf, eu já testei e estar em conformidade, se eu não me engano faltou só 1 campo que esta na documentação da v3.0, mas até que eu termine a realease isso já estará atualizado também, é só ir acompanhando, pode ir fazendo os testes se tiver alguma coisa a mais que possa contribuir eu agradeço desde já.

**Comment by amorales84** [comment]
Obrigado @robmachado e @maisonsakamoto , já testei e funcionou na v3.0.
