### ISSUE TITLE
Refatorar para sped-common v5.0

### ISSUE THREAD

**Issue by robmachado** [nfephp-org/sped-mdfe#63]
As classes 
Tools 
Make
devem ser refatoradas para usar a versão v5.0 do sped-common, desta forma garante compatibilidade com o sped-nfe.

Pontos importantes, do sped-common:
1 - Certificate::class
2 - Signer::class
3 - DomImproved::class
4 - Keys::class
5 - Soap/SoapCurl::class

Minha sugestão é refatorar enquanto está em dev ou passa esse banch v3.0, para master e subir um release, temporariamente e abrir um novo branch v.4.0 para essa refatoração que irá com certeza quebrar a compatibilidade com as versões anteriores.

**Comment by maisonsakamoto** [comment]
vou deixar a branch v3.0 do jeito que esta mesmo e vou criar a branch v4.0 para a refatoração, e usar a master quando tivermos uma versão estável já refatorada

**Comment by robmachado** [comment]
OK abra então a v4.0 que vejo no que posso ir ajudando

**Comment by maisonsakamoto** [comment]
não consigo criar só consegui no meu fork, se for fazer um PR ele só da opção de enviar p/ Master ou v3.0
ajuda eu ai...rsrsr
