### ISSUE TITLE
Multiplas NFes/CTes

### ISSUE THREAD

**Issue by lukinhaspm** [nfephp-org/sped-mdfe#70]
Boa tarde pessoal!

Estou começando com MDFe e CTe, tenho um cliente que gostaria de emitir MDFe (rodoviário), eu achei que era necessário ele usar o CTe também, mas pelo que pesquisei é possível usar apenas o MDFe.

Alguém já fez uma forma de adicionar várias NFes/CTes a um MDFe? 

Vou seguir meus testes, e se encontrar pontos para melhoria/exemplo vou contribuir.

Obrigado

**Comment by gustavodebiasi** [comment]
Sim, já é possível adicionar várias NF-es/CT-es.

**Comment by lukinhaspm** [comment]
@gustavodebiasi  tem algum exemplo? Além do que esta online...?

**Comment by olavocneto** [comment]
Segue pseudo código que espero ajudar a da uma ideia 💡na sequência de chamada dos métodos da classe Make pois esse é geralmente a maior dificuldade 🤔 que enfrento para que a montagem do Dom fique sem erros de acordo o xsd. E buscar todo do BD, variáveis, classes é um parte de cada aplicação ou framework. E também porque estou do cel 😀

```
função tagInfMunDescarg

        $municipios <- Busca municípios de descarregamento

Para cada município
            $makeMDF->tagInfMunDescarga($i, $cMunDescarga, $xMunDescarga);

            $nfes <- Buscas as NFe do município

            Para cada NF-e
                $makeMDF->tagInfNFe($i, $chNFe, $segCodBarra)
            

            $ctes <- Buscas as CTe do município

            Para cada CTe
                $makeMDF->tagInfCTe($nItem, $chCTe, $segCodBarra, $indReentrega);
           
Fim função
```
Abraço,

**Comment by lukinhaspm** [comment]
Obrigado @olavocneto, tenho o ERP funcionando com as informações para boa parte preencher!
A minha dúvida era essa mesmo, se baseado no exemplo, eu chamar mais vezes a tag de adicionar o NFe ja era o bastante... vou fazer uns testes e posto se deu certo!

**Comment by gustavodebiasi** [comment]
Claro @lukinhaspm, que nem olavo comentou, utilizo um laço chamando a mesma tag:
foreach ($cte->nfes as $nfe) {
    $resp = $cteMake->infNFeTag(
         $pChave = $nfe->chave_acesso,
         $PIN = '',
         $dPrev = $nfe->data_prevista_entrega
     );
}

**Comment by lukinhaspm** [comment]
Obrigado a todos, já estou gerando os xmls da MDFe!
