### ISSUE TITLE
Padrão de Desenvolvimento

### ISSUE THREAD

**Issue by jsalmeida1101** [nfephp-org/sped-mdfe#71]
Boa tarde, gostaria de utilizar o projeto e sendo assim vou ajudar no desenvolvimento para que possamos gerar uma verão estável. Ainda estou estudando o código e sobre o próprio MDF-e, mas me surgiu uma dúvida: os padrões de desenvolvimentos deverão ser seguidos igual ao restante do projeto? Como já citei, ainda estou estudando mas vi algumas diferenças em relação ao restante, como por exemplo, os parâmetros passados para gerar as tags do XML estão recebendo cada informação sendo passada individualmente, isso será ajustado para receber uma stdClass também?

**Comment by robmachado** [comment]
Sim os padrões de SPED-NFE devem ser usados neste e em outros projetos como o sped-cte

**Comment by jsalmeida1101** [comment]
Entendi, obrigado Roberto. 
Algum desenvolvedor que esteja mais ativo no projeto já está fazendo isso?

**Comment by robmachado** [comment]
Sim quem assumiu o projeto foram esses que fizeram as ultimas PRs

**Comment by jsalmeida1101** [comment]
Alguém que tem trabalhado nessa refatoração pode me deixar mais a par da situação? Como que anda o desenvolvimento nessa parte? Ou entra em contato comigo para que possamos nos alinhar nisso então.
