### ISSUE TITLE
Bom dia!

### ISSUE THREAD

**Issue by AllisonErd** [nfephp-org/sped-mdfe#73]
Primeiramente, parabéns pelo projeto!
Segundo, a biblioteca está habilitada para uso? Vi do README que esta apenas em testes.
Desde já agradeço!

**Comment by lukinhaspm** [comment]
Estou usando o 
composer require joaoroyosilva/sped-mdfe "^v4.0"

**Comment by AllisonErd** [comment]
Obrigado por responder @lukinhaspm . Teria algum meio de tirar umas duvidas com vc, só de como configurar a biblioteca para o uso?

**Comment by lukinhaspm** [comment]
Opa, cara posso tentar ajudar sim

Eu mesmo não sei como consegui kkkkk

chama no Skype

abs

Lucas Augusto Milanes
Skype: Lucas Augusto Milanes
Cel:     +55 (11) 98160-3130


Em ter, 23 de out de 2018 às 14:45, José Allison <notifications@github.com>
escreveu:

**Comment by AllisonErd** [comment]
Ok  @lukinhaspm irei falar com vc no skype. Obrigado mais uma vez!

**Comment by joaoroyosilva** [comment]
Esse meu fork eu só corrigi as dependências e acertei algumas partes da geração do XML. Só fiz isso para funcionar com a versão 5 da sped-nfe. Ainda não tive tempo de refatorar para usar as mesmas classes da nfe. Por enquanto está funcionando como se fosse um projeto diferente.
