### ISSUE TITLE
Produção MDF-e

### ISSUE THREAD

**Issue by ddennys** [nfephp-org/sped-mdfe#74]
Boa noite galera,

Sou novo no mundo fiscal e estou com uma dúvida sobre o sped-mdfe.
Já tenho implementado o sped-nfe só que o meu sped-common instalado no projeto esta com uma versão acima da que o sped-mdfe precisa. Tem alguma forma de utiliza os 2 no mesmo projeto?

Segui o erro quando dou o "composer require nfephp-org/sped-mdfe" ->

 Problem 1
    - Installation request for nfephp-org/sped-mdfe ^2.0 -> satisfiable by nfephp-org/sped-mdfe[v2.0].
    - Conclusion: remove nfephp-org/sped-common v5.0.30
    - Conclusion: don't install nfephp-org/sped-common v5.0.30
    - nfephp-org/sped-mdfe v2.0 requires nfephp-org/sped-common ^4.1 -> satisfiable by nfephp-org/sped-common[v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.1.x-dev].
    - Can only install one of: nfephp-org/sped-common[v4.1.0, v5.0.30].
    - Can only install one of: nfephp-org/sped-common[v4.1.1, v5.0.30].
    - Can only install one of: nfephp-org/sped-common[v4.1.10, v5.0.30].
    - Can only install one of: nfephp-org/sped-common[v4.1.11, v5.0.30].
    - Can only install one of: nfephp-org/sped-common[v4.1.12, v5.0.30].
    - Can only install one of: nfephp-org/sped-common[v4.1.13, v5.0.30].
    - Can only install one of: nfephp-org/sped-common[v4.1.14, v5.0.30].
    - Can only install one of: nfephp-org/sped-common[v4.1.15, v5.0.30].
    - Can only install one of: nfephp-org/sped-common[v4.1.2, v5.0.30].
    - Can only install one of: nfephp-org/sped-common[v4.1.3, v5.0.30].
    - Can only install one of: nfephp-org/sped-common[v4.1.4, v5.0.30].
    - Can only install one of: nfephp-org/sped-common[v4.1.5, v5.0.30].
    - Can only install one of: nfephp-org/sped-common[v4.1.6, v5.0.30].
    - Can only install one of: nfephp-org/sped-common[v4.1.7, v5.0.30].
    - Can only install one of: nfephp-org/sped-common[v4.1.8, v5.0.30].
    - Can only install one of: nfephp-org/sped-common[v4.1.9, v5.0.30].
    - Can only install one of: nfephp-org/sped-common[v4.1.x-dev, v5.0.30].
    - Installation request for nfephp-org/sped-common (locked at v5.0.30) -> satisfiable by nfephp-org/sped-common[v5.0.30].

**Comment by lukinhaspm** [comment]
Estou usando o 
composer require joaoroyosilva/sped-mdfe "^v4.0"

**Comment by ddennys** [comment]
a v4.0 já esta usual para produção?

**Comment by joaoroyosilva** [comment]
Esse meu fork eu só corrigi as dependências e acertei algumas partes da geração do XML. Só fiz isso para funcionar com a versão 5 da sped-nfe. Ainda não tive tempo de refatorar para usar as mesmas classes da nfe. Por enquanto está funcionando como se fosse um projeto diferente.

**Comment by cleitonperin** [comment]
foi reescrito o sped-mdfe para utilizar a mesma versão do sped-common do sped-nfe e sped-cte
