### ISSUE TITLE
Rejeição - 680: Município de descarregamento duplicado.

### ISSUE THREAD

**Issue by zahaila** [nfephp-org/sped-mdfe#79]
Ao adicionar vários documentos (NFe|CTe) para um mesmo manifesto, para cada um, uma tag `<infMunDescarga>` é inserida. Quando dois ou mais documentos têm o mesmo município como descarga, o manifesto é rejeitado tal como exemplificado [aqui](https://www.oobj.com.br/bc/article/rejei%C3%A7%C3%A3o-680-munic%C3%ADpio-de-descarregamento-duplicado-no-mdf-e-como-resolver-94.html).

**Comment by claytonaalves** [comment]
Aparentemente quando os documentos pertencem ao mesmo município eles devem ser agrupados dentro da tag `infMunDescarga` de cada município.

Em uma primeira análise do código, acredito que seria responsabilidade da função `zTagInfDoc` fazer este agrupamento.
