### ISSUE TITLE
630 - Rejeição: Falha no Schema XML específico para o evento

### ISSUE THREAD

**Issue by developerewt** [nfephp-org/sped-mdfe#8]
Estou fazendo testes com a biblioteca para uma possível implementação em um cliente e me deparei com o erro do título no momento de Encerramento de uma MDF-e, (consegui gerar MDF-e pela biblioteca). Teria como passar um parecer, baseado na sua experiência dos possíveis motivos desse erro retornar? Na internet existem pouquíssimos documentos sobre MDF-e e os que tem não são satisfatórios para essa finalidade!!!

Fiz a comparação do meu XML com o apresentado nesse [link](http://www.flexdocs.com.br/guiamdfe/WS.encerraMDFe.html), os dois XMLs são exatamente iguais. 

Desde já agradeço!!!

**Comment by robmachado** [comment]
Bom essa classe está em desenvolvimento não está indicada como estável ou funcional !!!

**Comment by developerewt** [comment]
Quanto ao fato de ser uma lib instável eu tenho ciência, por isso, mencionei que estou fazendo testes na mesma, porém, só gostaria de saber se você teria alguma dica para esse erro.
Mas de qualquer forma agradeço.

**Comment by robmachado** [comment]
Posso ajudar, mas você não me disse qual é o erro ???

**Comment by developerewt** [comment]
Bom, referente ao erro em si, a mesmagem é a apresentada no título, vou colocar o XML de retorno:

Vou te apresentar o XML que está sendo enviado:

`<mdfeDadosMsg xmlns="http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoEvento">
	<eventoMDFe xmlns="http://www.portalfiscal.inf.br/mdfe" versao="1.00">
		<infEvento Id="ID1101123516061414527200019458001000000003130009000101">
			<cOrgao>35</cOrgao>
			<tpAmb>2</tpAmb>
			<CNPJ>CNPJ_DA_EMPRESA</CNPJ>
			<chMDFe>351606141452720001945(...)000000031300090001</chMDFe>
			<dhEvento>2016-08-05T17:27:25</dhEvento>
			<tpEvento>110112</tpEvento>
			<nSeqEvento>1</nSeqEvento>
			<detEvento versaoEvento="1.00">
				<evEncMDFe>
					<descEvento>Encerramento</descEvento>
					<nProt>9351600000(...)</nProt>
					<dtEnc>2016-08-05T17:27:25</dtEnc>
					<cUF>35</cUF>
					<cMun>3550308</cMun>
				</evEncMDFe>
			</detEvento>
		</infEvento>
		<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
			<SignedInfo>
				<CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
				<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
				<Reference URI="#ID1101123516061414527200019458001000000003130009000101">
					<Transforms>
						<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
						<Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
					</Transforms>
					<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
					<DigestValue>nMFzIDZljdQraGkSg14hhi9IwFM=</DigestValue>
				</Reference>
			</SignedInfo>
			<SignatureValue>D/wct8A/P9PYUCYD... HASH GIGANTE</SignatureValue>
			<KeyInfo>
				<X509Data>
					<X509Certificate>MIIIRTCCBi2gA... HASH GIGANTE</X509Certificate>
				</X509Data>
			</KeyInfo>
		</Signature>
	</eventoMDFe>
</mdfeDadosMsg>`

Validei conforme no [link](http://www.flexdocs.com.br/guiamdfe/WS.encerraMDFe.html) apresentado e também validei as informações conforme a documentação, porém, dá erro, conforme abaixo:

`<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<soap:Header>
		<mdfeCabecMsg xmlns="http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoEvento">
			<cUF>35</cUF>
			<versaoDados>1.00</versaoDados>
		</mdfeCabecMsg>
	</soap:Header>
	<soap:Body>
		<mdfeRecepcaoEventoResult xmlns="http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoEvento">
			<retEventoMDFe xmlns="http://www.portalfiscal.inf.br/mdfe" versao="1.00">
				<infEvento Id="ID">
					<tpAmb>2</tpAmb>
					<verAplic>RS20160520154043</verAplic>
					<cOrgao>35</cOrgao>
					<cStat>630</cStat>
					<xMotivo>Rejeição: Falha no Schema XML específico para o evento</xMotivo>
				</infEvento>
			</retEventoMDFe>
		</mdfeRecepcaoEventoResult>
	</soap:Body>
</soap:Envelope>`

**Comment by robmachado** [comment]
Use o forum ou meu email para mandar os XML em anexo pois ... o erro é genérico demais 
Quando uma mensagem é enviada é necessário as vazes checar o envelope soap também.

Outra recomendação que eu faço é usar por ora a versão v3.10-obsoleta que acredito estar ainda funcional para MDFe.

https://github.com/nfephp-org/nfephp/tree/v3.10-obsoleto

**Comment by freitasgx** [comment]
Olá @developerewt  notei que o no seu xml a tag <dtEnc>2016-08-05T17:27:25</dtEnc> está com a hora.
Infelizmente no manual não deixa explicito porem é somente a data: <dtEnc>2016-08-05</dtEnc> testa lá e nos da um retorno, grande abraço!

**Comment by Rafabin** [comment]
Outro detalhe. No xml de envio o elemento dhEvento deve ser informado com o timezone.

**Comment by NewtonMan** [comment]
Só para registrar aqui que a biblioteca não estava fazendo o registro de encerramento devido a um problema na tag <dhEvento> do método zSefazEvento, é preciso inserir ao final da data o Timezone, se alterar a linha 862 conforme abaixo o encerramento já funcionará:
de
$dhEvento = (string) str_replace(' ', 'T', date('Y-m-d H:i:s'));
para
$dhEvento = (string) str_replace(' ', 'T', date('Y-m-d H:i:s')).'-02:00';

Vale lembra que eu fiz isso de maneira manual e o correto é que isso seja configurável ou possa ser obtido do ambiente.
