### ISSUE TITLE
Versão 3.00a

### ISSUE THREAD

**Issue by lukinhaspm** [nfephp-org/sped-mdfe#80]
Boa tarde pessoal

Alguém já ajustou a versão própria para a 3.00a? Com QR-code?
 
Abs

**Comment by robmachado** [comment]
Questione no forum é mais provável obter uma resposta de lá. https://groups.google.com/forum/#!forum/nfephp

**Comment by lukinhaspm** [comment]
Tem razão, me empolguei - ou desesperei como queira hahaha
