### ISSUE TITLE
sefazEvento - Erro para Emitente Pessoa Física

### ISSUE THREAD

**Issue by rafaels86** [nfephp-org/sped-mdfe#95]
Boa tarde, na função sefazEvento do arquivo Tools.php está sendo tratado somente o emitente com CNPJ, para fazer funcionar o envio fiz as adaptações:
- $this->config->cpf para buscar o CPF;
- "<CPF>$cpf</CPF>"ao invés do CNPJ na variável do $request.

**Comment by cleitonperin** [comment]
nao entendi, pode ser mais claro?

**Comment by rafaels86** [comment]
Sim, como estou emitindo MDF-e com um certificado digital de pessoa física, tive que fazer alguns ajustes para que funcionasse o envio:
1. na definição do array de configuração usado pela classe tools, troquei a chave cnpj por cpf;
2. no arquivo Tools.php do projeto sped-mdfe, função sefazEvento, troquei a linha 319 de "$cnpj = $this->config->cnpj" para "$cpf = $this->config->cpf";
3. na linha 329 troquei de ". "<CNPJ>$cnpj</CNPJ>"" para ". "<CPF>$cpf</CPF>"".

Só não adaptei a função para trabalhar com os dois tipos de documentos.

**Comment by rafaels86** [comment]
Agora que percebi que não está enviando as tags na postagem, mas enfim, no item 3 da minha resposta acima, troquei a tag CNPJ pela tag CPF.

**Comment by cleitonperin** [comment]
ola, seria interessante voce adaptar pra trabalhar com UM dos dois documentos e fazer o pull request
